import "./globals.css";
import Navber from "./component/Navber";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="relative">
        <div>
          <Navber></Navber>
        </div>
        <div className="flex ">
          {/* <Sideber className=''></Sideber> */}
          {children}
        </div>
      </body>
    </html>
  );
}
